alias ls='exa --color=auto -alF'
alias list='\ls --color=auto'
alias tree='exa --tree'
alias add='git add -A && git status'
alias df='df -h /dev/sda2'
alias ping='ping -c 1'
alias off='~/./off.sh'
alias texmk='~/./texmk.sh'
alias create='~/./create.sh'
alias pacman='sudo pacman'
alias npm='sudo npm'
alias commit='~/./commit.sh'
alias source='source ~/.bashrc'
alias sqlite='sqlite3'
alias fonts='fc-list'
alias sql='sudo -iu postgres'
